# Generated by Django 5.0.1 on 2026-01-16 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_friendship_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('games', 'Jeux'), ('entertainment', 'Divertissement'), ('social', 'Réseaux sociaux'), ('productivity', 'Productivité'), ('utilities', 'Utilitaires'), ('education', 'Éducation'), ('lifestyle', 'Style de vie'), ('finance', 'Finance'), ('health', 'Santé & Forme'), ('news', 'Actualités'), ('music', 'Musique'), ('photo_video', 'Photo & Vidéo'), ('shopping', 'Shopping'), ('travel', 'Voyages'), ('food', 'Nourriture & Boissons'), ('sports', 'Sports'), ('weather', 'Météo'), ('books', 'Livres'), ('business', 'Business'), ('developer', 'Développement'), ('graphics', 'Graphisme & Design'), ('kids', 'Enfants'), ('medical', 'Médical'), ('navigation', 'Navigation'), ('reference', 'Référence')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Material/SF Symbol", max_length=50)),
                ('color', models.CharField(default='#007AFF', help_text='Couleur hex de la catégorie', max_length=7)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='miniapp',
            options={'ordering': ['-featured', '-downloads_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='miniapp',
            name='age_rating',
            field=models.CharField(choices=[('4+', '4+'), ('9+', '9+'), ('12+', '12+'), ('17+', '17+')], default='4+', max_length=5),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='banner',
            field=models.ImageField(blank=True, help_text='Bannière 1200x630px', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mise en avant dans le store'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='featured_order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage si featured"),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='full_description',
            field=models.TextField(blank=True, help_text='Description complète avec changelog, fonctionnalités...'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='languages',
            field=models.CharField(default='fr', help_text='Codes langue séparés par virgules', max_length=200),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='Lien politique de confidentialité'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='size_bytes',
            field=models.BigIntegerField(default=0, help_text='Taille en octets'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='support_url',
            field=models.URLField(blank=True, help_text='Lien support'),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='website_url',
            field=models.URLField(blank=True, help_text="Site web de l'app"),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='whats_new',
            field=models.TextField(blank=True, help_text='Nouveautés de la dernière version'),
        ),
        migrations.AlterField(
            model_name='miniapp',
            name='description',
            field=models.TextField(help_text='Description courte'),
        ),
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('device_type', models.CharField(choices=[('phone', 'Téléphone'), ('tablet', 'Tablette'), ('desktop', 'Bureau')], default='phone', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='store.miniapp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='miniapp',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='store.category'),
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Note de 1 à 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('developer_response', models.TextField(blank=True)),
                ('developer_response_date', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, help_text="Version lors de l'avis", max_length=20)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.miniapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('app', 'user')},
            },
        ),
    ]
