# Generated by Django 5.0.1 on 2026-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_alter_miniapp_options_miniapp_age_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapp',
            name='genesis_project_id',
            field=models.UUIDField(blank=True, help_text='Linked Genesis project UUID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='miniapp',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('genesis', 'Genesis AI')], default='manual', max_length=10),
        ),
    ]
