# Generated by Django 5.0.1 on 2026-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_miniapp_genesis_project_id_miniapp_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapp',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Visible in the public Store'),
        ),
    ]
