# Generated by Django 5.0.1 on 2026-02-20 08:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenesisQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('creations_this_month', models.PositiveIntegerField(default=0)),
                ('month_reset_date', models.DateField(default=datetime.date.today)),
                ('extra_credits', models.PositiveIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64)),
                ('subscription_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('', 'None')], default='', max_length=10)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genesis_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genesis Quota',
            },
        ),
    ]
