# Generated by Django 5.0.1 on 2026-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0002_genesisquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisproject',
            name='deployed_version_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
