# Generated by Django 5.0.1 on 2026-02-18 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='social_stor_expires_2883fe_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', '-created_at'], name='social_stor_author__a99634_idx'),
        ),
    ]
